TOTAL_SCENARIOS = 1
TOTAL_ITERATIONS = 30
RESAMPLE = False
SAMPLE_SIZE = 10
MODEL_FDS_TOP_K = 10
# ACCURACY_ESTIMATION_SAMPLE_NUM = 1000 #directly sampled from dataset during dataprocessing for now
ACTIVE_LEARNING_CANDIDATE_INDICES_NUM = 400
STOCHASTIC_BEST_RESPONSE_CANDIDATE_INDICES_NUM = 400
STOCHASTIC_ACTIVE_LEARNING_CANDIDATE_INDICES_NUM = 400

STOCHASTIC_BEST_RESPONSE_GAMMA = 0.5
STOCHASTIC_UNCERTAINTY_SAMPLING_GAMMA = 0.5
